version: "3.9"

services:
  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres/userdb
    depends_on:
      - postgres

  catalog_service:
    build:
      context: .
      dockerfile: catalog_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres/catalogdb
    depends_on:
      - postgres

  playback_service:
    build:
      context: .
      dockerfile: playback_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres/playbackdb
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh:ro
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        sleep 5 &&
        psql -U postgres -c 'CREATE DATABASE userdb;' &&
        psql -U postgres -c 'CREATE DATABASE catalogdb;' &&
        psql -U postgres -c 'CREATE DATABASE playbackdb;' &&
        wait
      "

volumes:
  pgdata: